# Generated by Django 5.2.4 on 2025-09-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference_model', models.CharField(db_index=True, max_length=64)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detector.uploadedimage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('image', 'inference_model'), name='uniq_detection_per_image_model')],
            },
        ),
    ]
