# Generated by Django 5.2.4 on 2025-09-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='detections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
